/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/anfragen': RouteRecordInfo<'/anfragen', '/anfragen', Record<never, never>, Record<never, never>>,
    '/games/': RouteRecordInfo<'/games/', '/games', Record<never, never>, Record<never, never>>,
    '/games/flappybird/': RouteRecordInfo<'/games/flappybird/', '/games/flappybird', Record<never, never>, Record<never, never>>,
    '/games/flappybird/download/': RouteRecordInfo<'/games/flappybird/download/', '/games/flappybird/download', Record<never, never>, Record<never, never>>,
    '/games/flappybird/highscore/': RouteRecordInfo<'/games/flappybird/highscore/', '/games/flappybird/highscore', Record<never, never>, Record<never, never>>,
  }
}
