/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/games/': RouteRecordInfo<'/games/', '/games', Record<never, never>, Record<never, never>>,
    '/games/download/': RouteRecordInfo<'/games/download/', '/games/download', Record<never, never>, Record<never, never>>,
    '/games/download/flappyBird': RouteRecordInfo<'/games/download/flappyBird', '/games/download/flappyBird', Record<never, never>, Record<never, never>>,
    '/games/highscores/': RouteRecordInfo<'/games/highscores/', '/games/highscores', Record<never, never>, Record<never, never>>,
    '/games/highscores/flappyBird': RouteRecordInfo<'/games/highscores/flappyBird', '/games/highscores/flappyBird', Record<never, never>, Record<never, never>>,
  }
}
